import Auth from "@/components/Auth";
import Breadcrumb from "@/components/Breadcrumb";
import Footer from "@/components/Footer";
import Navbar from "@/components/Header/Navbar";
import Topbar from "@/components/Header/Topbar";
import Head from "next/head";

export default function Login() {
	return (
		<>
			<Head>
				<title>Login | Take My Order</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<section className="">
				<Topbar />
				<Navbar />
				<Breadcrumb />

				<div className="wrapper">
					<div className="w-6/12 mx-auto">
						<Auth />
					</div>
				</div>

				<Footer />
			</section>
		</>
	);
}
