# Generated by Django 4.1.5 on 2023-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_campaign_category_contact_remove_menu_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="OrderItems/"),
        ),
    ]
