# Generated by Django 4.1.5 on 2023-02-13 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_orderitem_name_alter_orderitem_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="resarvation",
            name="date",
            field=models.DateField(default=datetime.date(2023, 2, 13)),
            preserve_default=False,
        ),
    ]
