# Generated by Django 4.1.5 on 2023-02-16 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_resarvation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
