# Generated by Django 4.1.5 on 2023-02-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_campaign_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="resarvation",
            name="phone",
            field=models.CharField(default="01718925923", max_length=11),
            preserve_default=False,
        ),
    ]
