# Generated by Django 4.1.5 on 2023-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_resarvation_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resarvation",
            name="time",
            field=models.TimeField(),
        ),
    ]
