# Generated by Django 4.1.5 on 2023-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_resarvation_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="chefs/")),
                ("short_description", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AlterField(
            model_name="resarvation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("confirmed", "confirmed"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
