# Generated by Django 4.1.5 on 2023-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_emailsubscription_options_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
